### PR TITLE
Swift 4 Migration

### PR DESCRIPTION
**Pull request by Kalvin126**
- Swift 4 migration
- `Pods` folder added to `.gitignore` and is no longer checked in
- Project format updated to `Xcode 9.0`
- Updated to `SnapKit 4.0`, `Masonry 1.1.0`
- Resolve warnings

See commit log/messages for specific details/changes

### CODE REVIEW

**Comment by Kalvin126** [comment]
@jaredegan, @GriffinSchneider

**Comment by GriffinSchneider** [comment]
👍

**Comment by GriffinSchneider** [comment]
@Kalvin126 I just published `1.2.0` to CocoaPods

**Comment by Kalvin126** [comment]
Thanks!

**Pull request merged**
